# Copyright Contributors to the KubeTask project
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubetask-dogfooding

commonLabels:
  app.kubernetes.io/part-of: kubetask-dogfooding

resources:
  - base
  - resources
