# Copyright Contributors to the KubeTask project
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubetask-dogfood

resources:
  - namespace.yaml
  - rbac.yaml
  - secrets.yaml
  - agent-default.yaml
  - agent-dev.yaml
  - agent-dev-realtime.yaml
  - context-basic-rules.yaml
