{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubetask.fullname" . }}-webhook
  namespace: {{ include "kubetask.namespace" . }}
  labels:
    {{- include "kubetask.webhook.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
  - port: {{ .Values.webhook.service.port }}
    targetPort: webhook
    protocol: TCP
    name: webhook
    {{- if and (eq .Values.webhook.service.type "NodePort") .Values.webhook.service.nodePort }}
    nodePort: {{ .Values.webhook.service.nodePort }}
    {{- end }}
  {{- if .Values.webhook.service.metricsPort }}
  - port: {{ .Values.webhook.service.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  {{- end }}
  selector:
    {{- include "kubetask.webhook.selectorLabels" . | nindent 4 }}
{{- end }}
