# Copyright Contributors to the KubeTask project
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubetask-dogfooding

resources:
  - cronworkflow-go-update.yaml
  - webhooktrigger-github-comments.yaml
  - webhooktrigger-github-comments-dev.yaml
  - webhooktrigger-github-pr-review.yaml
