# Copyright Contributors to the KubeTask project
# EventBus provides the event transport layer for Argo Events.
# This uses NATS JetStream for reliable event delivery.
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: kubetask-system
spec:
  nats:
    native:
      replicas: 3
      auth: token
